---

default: &default
  adapter: mysql2
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  charset: utf8mb4
  encoding: utf8mb4
  timeout: 5000
  socket: /tmp/mysql.sock
development:
  <<: *default
test:
  <<: *default
  database: app
production:
  <<: *default
  database: app  
...

