---

default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  socket: /tmp/mysql.sock
  host: app-db
  port: 3306
  database: app
  username: app
  database: app 
  password: app

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default

...

